"use client";

export const DEMO_CONTRACT_ID = "airport_food_contract";

function normalizeContractId(contractId?: string) {
  return String(contractId || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function isDemoContractId(contractId?: string) {
  return normalizeContractId(contractId) === normalizeContractId(DEMO_CONTRACT_ID);
}

export const DEMO_CONTRACT = {
  contract_id: DEMO_CONTRACT_ID,
  name: "Airport Food Contract",
  contract_type: "Airline Catering Supplier Contract",
  parties: ["Airport Authority", "Concessionaire"],
  effective_date: "2026-01-01",
  currency: "USD",
};

type ContractLike = {
  contract_id: string;
  name?: string;
  [key: string]: unknown;
};

type ActualLike = {
  kpi_id?: string;
  source?: string;
  [key: string]: unknown;
};

type BreachLike = {
  breach_id?: string;
  kpi_id?: string;
  data_source?: string;
  [key: string]: unknown;
};

export const CONNECTED_SOURCES = [
  {
    id: "erp",
    label: "SAP S/4HANA Dispatch",
    type: "ERP",
    status: "Connected",
    records: "1,284 flights",
    description: "Catering orders, flight legs, and delivery scan timestamps",
  },
  {
    id: "rest",
    label: "AIDX / IoT REST Feed",
    type: "API",
    status: "Connected",
    records: "Live pulls",
    description: "Flight-event messages, cart temperature telemetry, and safety signals",
  },
  {
    id: "excel",
    label: "SFTP Ops Workbooks",
    type: "File Feed",
    status: "Reviewed",
    records: "Daily ops files",
    description: "Daily reconciliation files for orders, packaging, and quality checks",
  },
  {
    id: "service",
    label: "ServiceNow Incident Queue",
    type: "ITSM",
    status: "Connected",
    records: "INC queue",
    description: "Food-safety incidents, emergency response tickets, and owner actions",
  },
];

const baseKpi = {
  contract_id: DEMO_CONTRACT_ID,
  aggregation_type: "avg",
  confidence: 1,
  party: "Concessionaire",
  contact_email: "supplier-ops@example.com",
};

export const DEMO_KPIS = [
  {
    ...baseKpi,
    kpi_id: "KPI-001",
    name: "KPI-1: On-Time Delivery Performance Target",
    kpi_type: "sla",
    operator: ">=",
    value: "98.5",
    value_min: 98.5,
    value_max: null,
    unit: "%",
    section: "Section 4.02: KPI-1: On-Time Delivery Performance",
    structural_path: "ARTICLE IV > Section 4.02",
    trigger_condition: "Meals delivered within the catering window",
    remediation: "Submit RCA within 7 days and CAP within 15 days.",
    remediation_sla: "7 days",
    consequence_value: null,
    consequence_unit: null,
    clause_text: "Target: >= 98.5% on-time delivery. Delivery timestamp recorded at aircraft door or catering facility.",
  },
  {
    ...baseKpi,
    kpi_id: "KPI-002",
    name: "KPI-2: Meal Delivery Time Accuracy",
    kpi_type: "sla",
    operator: "==",
    value: "100",
    value_min: 100,
    value_max: null,
    unit: "%",
    section: "Section 4.03: KPI-2: Meal Delivery Time Accuracy",
    structural_path: "ARTICLE IV > Section 4.03",
    trigger_condition: "Meals arrive no earlier than 4 hours and no later than 90 minutes before departure",
    remediation: "Conduct operational review for repeated delivery-window misses.",
    remediation_sla: "15 days",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    kpi_id: "KPI-003",
    name: "KPI-3: Order Fulfillment Rate Target",
    kpi_type: "sla",
    operator: ">=",
    value: "99.5",
    value_min: 99.5,
    value_max: null,
    unit: "%",
    section: "Section 4.04: KPI-3: Order Fulfillment Rate",
    structural_path: "ARTICLE IV > Section 4.04",
    trigger_condition: "Ordered meals successfully delivered",
    remediation: "Process passenger meal refunds within 48 hours; repeated shortfalls trigger contract review.",
    remediation_sla: "48 hours",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    kpi_id: "KPI-004",
    name: "KPI-4: Meal Quality Score Target",
    kpi_type: "sla",
    operator: ">=",
    value: "4.5",
    value_min: 4.5,
    value_max: null,
    unit: "score",
    section: "Section 4.05: KPI-4: Meal Quality Score",
    structural_path: "ARTICLE IV > Section 4.05",
    trigger_condition: "Composite passenger, crew, and quality-audit score",
    remediation: "Submit CAP if the composite score falls below 3.5.",
    remediation_sla: "15 days",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    kpi_id: "KPI-005",
    name: "KPI-5: Special Meal Availability Target",
    kpi_type: "sla",
    operator: ">=",
    value: "99.0",
    value_min: 99,
    value_max: null,
    unit: "%",
    section: "Section 4.06: KPI-5: Special Meal Availability",
    structural_path: "ARTICLE IV > Section 4.06",
    trigger_condition: "Special meal requests fulfilled correctly",
    remediation: "Submit CAP for allergen errors; immediate suspension for medical-intervention errors.",
    remediation_sla: "Immediate",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    kpi_id: "KPI-006",
    name: "KPI-6: Temperature Compliance Target",
    kpi_type: "sla",
    operator: "==",
    value: "100",
    value_min: 100,
    value_max: null,
    unit: "%",
    section: "Section 4.07: KPI-6: Temperature Compliance",
    structural_path: "ARTICLE IV > Section 4.07",
    trigger_condition: "Meals meet temperature safety standards at time of service",
    remediation: "Replace affected meals and run a mandatory audit for repeated violations.",
    remediation_sla: "Immediate",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    aggregation_type: "sum",
    kpi_id: "KPI-007",
    name: "KPI-7: Food Safety Incident Rate Target",
    kpi_type: "sla",
    operator: "==",
    value: "0",
    value_min: 0,
    value_max: null,
    unit: "incidents",
    section: "Section 4.08: KPI-7: Food Safety Incident Rate",
    structural_path: "ARTICLE IV > Section 4.08",
    trigger_condition: "Confirmed foodborne illness incidents per million meals",
    remediation: "Report incidents to health department within 4 hours and complete investigation.",
    remediation_sla: "4 hours",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    kpi_id: "KPI-008",
    name: "KPI-8: Load Factor Flexibility",
    kpi_type: "sla",
    operator: "==",
    value: "100",
    value_min: 100,
    value_max: null,
    unit: "%",
    section: "Section 4.09: KPI-8: Load Factor Flexibility",
    structural_path: "ARTICLE IV > Section 4.09",
    trigger_condition: "Accommodate load-factor changes with at least 4 hours notice",
    remediation: "Submit RCA and CAP for missed load-factor changes.",
    remediation_sla: "7 days",
    consequence_value: 50,
    consequence_unit: "USD per meal",
  },
  {
    ...baseKpi,
    aggregation_type: "latest",
    kpi_id: "KPI-011",
    name: "KPI-11: Crew Meal Delivery Time",
    kpi_type: "sla",
    operator: ">=",
    value: "30",
    value_min: 30,
    value_max: null,
    unit: "minutes",
    section: "Section 4.12: KPI-11: Crew Meal Compliance",
    structural_path: "ARTICLE IV > Section 4.12",
    trigger_condition: "Delivery at least 30 minutes before crew report time",
    remediation: "Submit RCA and CAP.",
    remediation_sla: "7 days",
    consequence_value: 50,
    consequence_unit: "USD per meal",
  },
  {
    ...baseKpi,
    kpi_id: "KPI-012",
    name: "KPI-12: Documentation Accuracy Target",
    kpi_type: "sla",
    operator: "==",
    value: "100",
    value_min: 100,
    value_max: null,
    unit: "%",
    section: "Section 4.13: KPI-12: Documentation Accuracy",
    structural_path: "ARTICLE IV > Section 4.13",
    trigger_condition: "Meal manifests, allergen declarations, and nutrition information are accurate",
    remediation: "Mandatory audit for repeated documentation errors.",
    remediation_sla: "15 days",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    aggregation_type: "latest",
    kpi_id: "KPI-014",
    name: "KPI-14: Emergency Response Contact",
    kpi_type: "sla",
    operator: "<=",
    value: "30",
    value_min: 30,
    value_max: null,
    unit: "minutes",
    section: "Section 4.15: KPI-14: Emergency Response",
    structural_path: "ARTICLE IV > Section 4.15",
    trigger_condition: "Response to emergency request within 30 minutes",
    remediation: "Submit RCA and CAP.",
    remediation_sla: "7 days",
    consequence_value: 1000,
    consequence_unit: "USD",
  },
  {
    ...baseKpi,
    kpi_id: "KPI-015-A",
    name: "KPI-15: Sustainable Packaging Target",
    kpi_type: "sla",
    operator: ">=",
    value: "50",
    value_min: 50,
    value_max: null,
    unit: "%",
    section: "Section 4.16: KPI-15: Sustainability Metrics",
    structural_path: "ARTICLE IV > Section 4.16",
    trigger_condition: "50% of packaging biodegradable or recyclable by 2028",
    remediation: "Submit annual sustainability improvement plan.",
    remediation_sla: "30 days",
    consequence_value: 50000,
    consequence_unit: "USD per year",
  },
  {
    ...baseKpi,
    aggregation_type: "latest",
    kpi_id: "FIN-001",
    name: "Business Class Base Rate",
    kpi_type: "financial",
    operator: "between",
    value: "28.50 - 42.00",
    value_min: 28.5,
    value_max: 42,
    unit: "USD",
    section: "Section 3.01: Base Meal Rates",
    structural_path: "ARTICLE III > Section 3.01",
    trigger_condition: "Base rate per business class meal",
    remediation: "Review billing line item and correct invoice.",
    remediation_sla: "7 days",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    party: "Grantor",
    aggregation_type: "latest",
    kpi_id: "FIN-002",
    name: "Late Payment Penalty",
    kpi_type: "financial",
    operator: "==",
    value: "1.5",
    value_min: 1.5,
    value_max: null,
    unit: "%",
    section: "Section 3.03: Payment Terms",
    structural_path: "ARTICLE III > Section 3.03",
    trigger_condition: "Invoices not paid within 30 days",
    remediation: "Pay outstanding balance plus accrued interest.",
    remediation_sla: "15 days",
    consequence_value: 1.5,
    consequence_unit: "% per month",
  },
  {
    ...baseKpi,
    aggregation_type: "latest",
    kpi_id: "TIM-001",
    name: "Daily Reporting Deadline",
    kpi_type: "timeline",
    operator: "<=",
    value: "10:00",
    value_min: null,
    value_max: null,
    unit: "AM",
    section: "Section 6.01: Daily Reporting",
    structural_path: "ARTICLE VI > Section 6.01",
    trigger_condition: "Daily reports submitted by 10:00 AM",
    remediation: "Submit missing report immediately and explain delay.",
    remediation_sla: "2 hours",
    consequence_value: null,
    consequence_unit: null,
  },
  {
    ...baseKpi,
    aggregation_type: "latest",
    kpi_id: "TIM-002",
    name: "Monthly Reporting Deadline",
    kpi_type: "timeline",
    operator: "<=",
    value: "10",
    value_min: 10,
    value_max: null,
    unit: "day of month",
    section: "Section 6.02: Monthly Reporting",
    structural_path: "ARTICLE VI > Section 6.02",
    trigger_condition: "Monthly report due by the 10th",
    remediation: "Submit missing report immediately.",
    remediation_sla: "24 hours",
    consequence_value: null,
    consequence_unit: null,
  },
];

const DEMO_ACTUAL_SERIES: Array<{
  kpi_id: string;
  unit: string;
  source: string;
  source_type: string;
  records: Array<{ timestamp: string; value: number; metadata: Record<string, string | number> }>;
}> = [
  {
    kpi_id: "KPI-001",
    unit: "%",
    source: "ERP flight catering operations",
    source_type: "ERP",
    records: [
      { timestamp: "2026-05-12T08:15:00Z", value: 99.1, metadata: { flight: "NQ401", station: "JFK", feed: "catering_dispatch" } },
      { timestamp: "2026-05-13T08:15:00Z", value: 98.8, metadata: { flight: "NQ405", station: "LGA", feed: "catering_dispatch" } },
      { timestamp: "2026-05-14T08:15:00Z", value: 98.6, metadata: { flight: "NQ409", station: "EWR", feed: "catering_dispatch" } },
      { timestamp: "2026-05-15T08:15:00Z", value: 98.1, metadata: { flight: "NQ410", station: "JFK", feed: "catering_dispatch" } },
      { timestamp: "2026-05-16T08:15:00Z", value: 97.7, metadata: { flight: "NQ411", station: "JFK", feed: "catering_dispatch" } },
      { timestamp: "2026-05-17T08:15:00Z", value: 97.4, metadata: { flight: "NQ412", station: "JFK", feed: "catering_dispatch" } },
      { timestamp: "2026-05-18T08:15:00Z", value: 96.9, metadata: { flight: "NQ415", station: "BOS", feed: "catering_dispatch" } },
      { timestamp: "2026-05-19T08:15:00Z", value: 96.5, metadata: { flight: "NQ418", station: "JFK", feed: "catering_dispatch" } },
      { timestamp: "2026-05-20T08:15:00Z", value: 96.4, metadata: { flight: "NQ420", station: "DCA", feed: "catering_dispatch" } },
      { timestamp: "2026-05-21T08:15:00Z", value: 96.2, metadata: { flight: "NQ412", station: "JFK", feed: "catering_dispatch" } },
    ],
  },
  {
    kpi_id: "KPI-003",
    unit: "%",
    source: "Excel daily order reconciliation",
    source_type: "Excel",
    records: [
      { timestamp: "2026-05-12T11:30:00Z", value: 99.8, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-512" } },
      { timestamp: "2026-05-13T11:30:00Z", value: 99.7, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-513" } },
      { timestamp: "2026-05-14T11:30:00Z", value: 99.6, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-514" } },
      { timestamp: "2026-05-15T11:30:00Z", value: 99.4, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-515" } },
      { timestamp: "2026-05-16T11:30:00Z", value: 99.3, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-516" } },
      { timestamp: "2026-05-17T11:30:00Z", value: 99.2, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-517" } },
      { timestamp: "2026-05-18T11:30:00Z", value: 99.0, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-518" } },
      { timestamp: "2026-05-19T11:30:00Z", value: 98.9, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-519" } },
      { timestamp: "2026-05-20T11:30:00Z", value: 99.1, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-520" } },
      { timestamp: "2026-05-21T11:30:00Z", value: 98.9, metadata: { sheet: "order_fulfillment_may", reviewer: "Ops QA", batch: "OF-521" } },
    ],
  },
  {
    kpi_id: "KPI-006",
    unit: "%",
    source: "IoT temperature REST endpoint",
    source_type: "REST",
    records: [
      { timestamp: "2026-05-12T12:05:00Z", value: 100, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-80", station: "JFK" } },
      { timestamp: "2026-05-13T12:05:00Z", value: 100, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-81", station: "LGA" } },
      { timestamp: "2026-05-14T12:05:00Z", value: 99.4, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-82", station: "EWR" } },
      { timestamp: "2026-05-15T12:05:00Z", value: 99.0, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-83", station: "JFK" } },
      { timestamp: "2026-05-16T12:05:00Z", value: 98.8, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-84", station: "JFK" } },
      { timestamp: "2026-05-17T12:05:00Z", value: 98.1, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-85", station: "BOS" } },
      { timestamp: "2026-05-18T12:05:00Z", value: 98.4, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-86", station: "DCA" } },
      { timestamp: "2026-05-19T12:05:00Z", value: 97.9, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-87", station: "JFK" } },
      { timestamp: "2026-05-20T12:05:00Z", value: 98.2, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-88", station: "EWR" } },
      { timestamp: "2026-05-21T12:05:00Z", value: 97.5, metadata: { endpoint: "/temperature/audit", sensor_batch: "T-88", station: "JFK" } },
    ],
  },
  {
    kpi_id: "KPI-014",
    unit: "minutes",
    source: "ServiceNow emergency response API",
    source_type: "Ticketing",
    records: [
      { timestamp: "2026-05-12T14:22:00Z", value: 24, metadata: { ticket: "INC-7391", queue: "Emergency Response" } },
      { timestamp: "2026-05-13T14:22:00Z", value: 26, metadata: { ticket: "INC-7398", queue: "Emergency Response" } },
      { timestamp: "2026-05-14T14:22:00Z", value: 28, metadata: { ticket: "INC-7403", queue: "Emergency Response" } },
      { timestamp: "2026-05-15T14:22:00Z", value: 31, metadata: { ticket: "INC-7408", queue: "Emergency Response" } },
      { timestamp: "2026-05-16T14:22:00Z", value: 35, metadata: { ticket: "INC-7412", queue: "Emergency Response" } },
      { timestamp: "2026-05-17T14:22:00Z", value: 34, metadata: { ticket: "INC-7415", queue: "Emergency Response" } },
      { timestamp: "2026-05-18T14:22:00Z", value: 39, metadata: { ticket: "INC-7418", queue: "Emergency Response" } },
      { timestamp: "2026-05-19T14:22:00Z", value: 41, metadata: { ticket: "INC-7419", queue: "Emergency Response" } },
      { timestamp: "2026-05-20T14:22:00Z", value: 38, metadata: { ticket: "INC-7420", queue: "Emergency Response" } },
      { timestamp: "2026-05-21T14:22:00Z", value: 42, metadata: { ticket: "INC-7421", queue: "Emergency Response" } },
    ],
  },
  {
    kpi_id: "KPI-015-A",
    unit: "%",
    source: "Supplier sustainability workbook",
    source_type: "Excel",
    records: [
      { timestamp: "2026-05-12T15:10:00Z", value: 49.2, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-13T15:10:00Z", value: 48.6, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-14T15:10:00Z", value: 48.0, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-15T15:10:00Z", value: 47.5, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-16T15:10:00Z", value: 47.0, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-17T15:10:00Z", value: 46.8, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-18T15:10:00Z", value: 45.9, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-19T15:10:00Z", value: 45.2, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-20T15:10:00Z", value: 44.8, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
      { timestamp: "2026-05-21T15:10:00Z", value: 44, metadata: { workbook: "packaging_mix_q2", tab: "May trend" } },
    ],
  },
  {
    kpi_id: "KPI-007",
    unit: "incidents",
    source: "Food safety incident REST endpoint",
    source_type: "REST",
    records: [
      { timestamp: "2026-05-12T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-13T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-14T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-15T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-16T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-17T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-18T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-19T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-20T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
      { timestamp: "2026-05-21T16:00:00Z", value: 0, metadata: { endpoint: "/food-safety/incidents", region: "Northeast" } },
    ],
  },
  {
    kpi_id: "TIM-001",
    unit: "hour",
    source: "Daily reporting portal",
    source_type: "Portal",
    records: [
      { timestamp: "2026-05-12T10:00:00Z", value: 9.3, metadata: { report_id: "DR-512", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-13T10:00:00Z", value: 9.5, metadata: { report_id: "DR-513", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-14T10:00:00Z", value: 9.7, metadata: { report_id: "DR-514", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-15T10:00:00Z", value: 9.8, metadata: { report_id: "DR-515", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-16T10:00:00Z", value: 10.1, metadata: { report_id: "DR-516", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-17T10:00:00Z", value: 9.9, metadata: { report_id: "DR-517", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-18T10:00:00Z", value: 9.8, metadata: { report_id: "DR-518", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-19T10:00:00Z", value: 9.6, metadata: { report_id: "DR-519", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-20T10:00:00Z", value: 9.4, metadata: { report_id: "DR-520", submitted_by: "Supplier Ops" } },
      { timestamp: "2026-05-21T10:00:00Z", value: 9.5, metadata: { report_id: "DR-521", submitted_by: "Supplier Ops" } },
    ],
  },
];

export const DEMO_ACTUALS = DEMO_ACTUAL_SERIES.flatMap((series) =>
  series.records.map((record, index) => ({
    actual_id: `demo-${series.kpi_id.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${String(index + 1).padStart(2, "0")}`,
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: series.kpi_id,
    value: record.value,
    unit: series.unit,
    timestamp: record.timestamp,
    source: series.source,
    metadata: {
      source_type: series.source_type,
      ...record.metadata,
    },
  }))
);

export const DEMO_BREACHES = [
  {
    breach_id: "demo-breach-kpi-015",
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: "KPI-015-A",
    actual_value: 44,
    threshold_value: 50,
    operator: ">=",
    is_breach: true,
    penalty_triggered: "50% biodegradable or recyclable packaging by 2028",
    penalty_amount: 50000,
    remediation: "Submit annual sustainability improvement plan.",
    remediation_sla: "30 days",
    sample_count: 1,
    status: "Open",
    notes: "Supplier to provide packaging substitution plan and forecasted conversion date.",
    timestamp: "2026-05-21T15:10:00Z",
    severity: "CRITICAL",
    data_source: "Supplier sustainability workbook",
  },
  {
    breach_id: "demo-breach-kpi-014",
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: "KPI-014",
    actual_value: 42,
    threshold_value: 30,
    operator: "<=",
    is_breach: true,
    penalty_triggered: "Emergency request response within 30 minutes",
    penalty_amount: 1000,
    remediation: "Submit RCA and CAP.",
    remediation_sla: "7 days",
    sample_count: 1,
    status: "Open",
    notes: "Emergency contact queue missed target by 12 minutes.",
    timestamp: "2026-05-20T14:22:00Z",
    severity: "HIGH",
    data_source: "ServiceNow emergency response API",
  },
  {
    breach_id: "demo-breach-kpi-006",
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: "KPI-006",
    actual_value: 97.5,
    threshold_value: 100,
    operator: "==",
    is_breach: true,
    penalty_triggered: "Temperature safety compliance at service",
    penalty_amount: 0,
    remediation: "Replace affected meals and run a mandatory audit for repeated violations.",
    remediation_sla: "Immediate",
    sample_count: 1,
    status: "In Progress",
    notes: "QA reviewing sensor batch T-88.",
    timestamp: "2026-05-19T12:05:00Z",
    severity: "MEDIUM",
    data_source: "IoT temperature REST endpoint",
  },
  {
    breach_id: "demo-breach-kpi-003",
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: "KPI-003",
    actual_value: 98.9,
    threshold_value: 99.5,
    operator: ">=",
    is_breach: true,
    penalty_triggered: "Ordered meals successfully delivered",
    penalty_amount: 0,
    remediation: "Process passenger meal refunds within 48 hours; repeated shortfalls trigger contract review.",
    remediation_sla: "48 hours",
    sample_count: 1,
    status: "In Progress",
    notes: "Ops QA reconciling order file variance.",
    timestamp: "2026-05-18T11:30:00Z",
    severity: "MEDIUM",
    data_source: "Excel daily order reconciliation",
  },
  {
    breach_id: "demo-breach-kpi-001",
    contract_id: DEMO_CONTRACT_ID,
    kpi_id: "KPI-001",
    actual_value: 96.2,
    threshold_value: 98.5,
    operator: ">=",
    is_breach: true,
    penalty_triggered: "Meals delivered within the catering window",
    penalty_amount: 0,
    remediation: "Submit RCA within 7 days and CAP within 15 days.",
    remediation_sla: "7 days",
    sample_count: 1,
    status: "Open",
    notes: "JFK station delay on flight NQ412.",
    timestamp: "2026-05-17T08:15:00Z",
    severity: "MEDIUM",
    data_source: "ERP flight catering operations",
  },
];

export function prepareDemoContracts(activeContracts: ContractLike[] = []) {
  const found = activeContracts.find((contract) => isDemoContractId(contract?.contract_id));
  const rest = activeContracts.filter((contract) => !isDemoContractId(contract?.contract_id));
  return [
    {
      ...DEMO_CONTRACT,
      ...(found || {}),
      name: "Airport Food Contract",
      contract_type: "Airline Catering Supplier Contract",
    },
    ...rest,
  ];
}

export function attachActualSourcesToBreaches(breaches: BreachLike[], actuals: ActualLike[]) {
  return breaches.map((breach) => {
    const actual = actuals.find((item) => item.kpi_id === breach.kpi_id);
    return actual ? { ...breach, data_source: breach.data_source || actual.source } : breach;
  });
}

export function demoTimeSeries(kpiId: string) {
  const thresholdByKpi: Record<string, number> = {
    "KPI-001": 98.5,
    "KPI-003": 99.5,
    "KPI-006": 100,
    "KPI-014": 30,
    "KPI-015-A": 50,
  };
  const series = DEMO_ACTUAL_SERIES.find((item) => item.kpi_id === kpiId);
  const values = series?.records || [
    { timestamp: "2026-05-17T08:00:00Z", value: 98, metadata: {} },
    { timestamp: "2026-05-18T08:00:00Z", value: 98.3, metadata: {} },
    { timestamp: "2026-05-19T08:00:00Z", value: 97.9, metadata: {} },
    { timestamp: "2026-05-20T08:00:00Z", value: 98.1, metadata: {} },
    { timestamp: "2026-05-21T08:00:00Z", value: 97.7, metadata: {} },
  ];

  return {
    data: values.map((record, index) => ({
      timestamp: record.timestamp,
      value: record.value,
      unit: series?.unit || (kpiId === "KPI-014" ? "minutes" : "%"),
      source: series?.source || (index % 2 === 0 ? "ERP flight catering operations" : "REST monitoring endpoint"),
    })),
    trend: {
      threshold: thresholdByKpi[kpiId] || 98.5,
    },
    breaches: DEMO_BREACHES.filter((breach) => breach.kpi_id === kpiId),
  };
}

export function buildDemoBreachEmail(breachId: string) {
  const breach = DEMO_BREACHES.find((item) => item.breach_id === breachId) || DEMO_BREACHES[0];
  const kpi = DEMO_KPIS.find((item) => item.kpi_id === breach.kpi_id);
  const unit = kpi?.unit || "";

  return {
    suggested_to: "supplier-ops@example.com",
    subject: `Escalation: Airport Food Contract - ${kpi?.name || breach.kpi_id}`,
    body: [
      "Dear Supplier Operations Team,",
      "",
      `Contract Performance Dashboard has flagged ${kpi?.name || breach.kpi_id} under the Airport Food Contract.`,
      `Actual performance: ${breach.actual_value}${unit}. Contract threshold: ${breach.operator} ${breach.threshold_value}${unit}.`,
      `Source reviewed: ${breach.data_source}.`,
      `Penalty exposure: $${breach.penalty_amount.toLocaleString()}.`,
      "",
      `Required remediation: ${breach.remediation} Response SLA: ${breach.remediation_sla}.`,
      "",
      "Please confirm ownership, root cause, and corrective action timing.",
      "",
      "Regards,",
      "Contract Management Office",
    ].join("\n"),
  };
}
